feeds:
  - url: "https://www.spreaker.com/show/4228834/episodes/feed"
    name: "The Answer"
  - url: "https://www.spreaker.com/show/4227531/episodes/feed"
    name: "Osim Historia"

site_settings:

  title: "Podtext"

  base_url: "https://mat-mo.github.io/podtext"


