feeds:
  - url: "https://feeds.simplecast.com/54nAGcIl"
    name: "The Daily"
  - url: "https://www.osimhistoria.com/theanswer/podcast.xml"
    name: "The Answer"
  
site_settings:
  title: "My Podcast Transcripts"
  base_url: "https://mat-mo.github.io/podtext"

# Token is now loaded from .env file or environment variable
hf_token: "${HF_TOKEN}"
