feeds:
  - url: "https://www.spreaker.com/show/4552198/episodes/feed"
    name: "Osim Historia"
  
site_settings:
  title: "My Podcast Transcripts"
  base_url: "https://mat-mo.github.io/podtext"

# Token is now loaded from .env file or environment variable
hf_token: "${HF_TOKEN}"
